### ISSUE TITLE
cannot compile on Xubuntu 13.10

### ISSUE THREAD

**Issue by gwijayas** [ahupp/mural#2]
Using Xubuntu 13.10, these the error messages:

``` bash
$ make
/usr/bin/g++ -Wall -O3 *.cpp -lrt -o mural_server
mural_server.cpp: In function ‘void read_inotify_events(int, const string&, std::vector<TagInfo>&)’:
mural_server.cpp:85:51: error: ‘read’ was not declared in this scope
   int len = enforce(read(inotify_fd, buf, BUF_SIZE), "read");
                                                   ^
make: *** [mural_server] Error 1
```

have installed `libinotifytools0-dev 3.14`
